language: cpp
sudo: required
dist: xenial
compiler:
- clang
os:
- linux
services:
- docker
before_install:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- bash ./build_deps/docker_build.sh
script:
- docker run --rm -v "${TRAVIS_BUILD_DIR}":/nightingale connorj/nightingale_build
  /bin/sh -c 'cd /nightingale && make'
after_success:
- bash ./build_deps/docker_push.sh
addons:
  artifacts:
    paths:
    - "${TRAVIS_BUILD_DIR}/ngos64.iso"
    target_paths:
    - /$(git describe --tags)
    - /latest