language: cpp
sudo: required
dist: xenial
os:
- linux
services:
- docker
script:
- bash ./build_deps/docker_build.sh
addons:
  artifacts:
    paths:
    - "${TRAVIS_BUILD_DIR}/ngos64.iso"
    - "${TRAVIS_BUILD_DIR}/ngos32.iso"
    target_paths:
    - "/$(git describe --tags)"
    - "/latest"
env:
  matrix:
  - ARCH=X86_64
  - ARCH=I686
  global:
  - DOCKER_USERNAME=connorj
  - secure: i8+PeYgiGJDQ7VADgzwa7J65Q0XkacJ0g0XkeCrk9Miih43OW8IEoPCsdUL8Ozp09UiG7NlrnwQHMH3aqFF7xqJ2ylE05yOMDgC77zswPZGgTF7AnYSM3xDF/U9JWVA1SK/I+1FhImgeui4mDCeOpdqGjWYGybeC47WvKCZiGUAgT2P3AMePemLVzoVlZMTdYSqYE/p97+0pllcmxAf38luHPqVLUAt04ekMIj59pDitvQGgcN2nlM66SjR97j8OU7C6auFZ3ofCV2OJv1Af3jwTmN2xszesVOayAJOTSUdQq0JNbOlT/shu9OV+7XaC/U5nTX2WMbvumFTsnqB3uvHdyeUUJoLECZ01s0yIU2eFzV2gkgkODTVFoMYvhI3+duP02KAjT/E9ra2bL9apTm8jt5urjdV65yHVBypyT28Xey+I9qnR5M8IQMuzfjdmjL7Vf4N0bmiTrySzqQC8wwYzm6P78Fmd3kN0kZDfQO9WpMqYFpSsM7Fg6Eg7yjp6AzmCIJTe2lRhm4B6Z2LHmyMFywsZfNrOYNkTTNaQlJd6qAP0ScH5aNtXe7kSTF5b14pOdfpPNW+vhFDhb2ClfvMFEw0d6USDISEKDHjIk/lET1LtW3ijuXqctBRrhYlf1ZL/LFHY0is9FKbyXqDXNVi2FkQZEeBY599tLc+QPB4=
  - secure: pRJGvoqFFvMA03O9q4smodXVrzxs0Ba+YS5qg6HdFHvzQf60q/tjnJt6uLVJN6gmlcZDhpVRLSKLxHVKqxfPxThbz0xRZ7a2oGiEqoSzB0kXomCQrgwDBdXKZCJpXycbd1yfhBi4tw2TXuzcHsnpR4vO8vbN4saX2Y7yvhmht9H0fU4RINrY3Yjd2/n7TW9m0U/kK1cpKS6j+NqYVBy0HOHO6W4HnHvHcTBNgU/RKyP3xNY2gCgYXbbiOiVgzISsySNanh/UfGoWXzWHMnFzsInIMiRuL7E3jqiXzW0pqPO+57AMg2dl+A0jydHIMgaqjH8QKiwbGxTo8dwlaJ8BAe6mMugf9gJASuA4alf1obLR6jkFTd3xXecE6uqPS2bMHwPRbV31PJHjgOltnIKx68PkFsz+ivC1sxKEfbhd3qI5ZQhHk7hTklYotk3BllTduS2gs6JMXvN18zpIneb9KDQui0T5WM419vw79XQm9wVm4KzGf5VwF0CGt2RiCW/xCspvXSi0hxbWeAtcP5QcVajL2oF3dKjzBWoTeAU1TMwcpDq/JdoCUnpSY4VvhgFAhtpTMOAk9XytAkV9pJ5w5BHmhKRY3q7kE9gTVxVD0zsqqyTNG30xpMf6rQD351XOZjagMjWvkzZvamXjCjIYnJa97xg+lz8vWUT1tnrDZxQ=
  - secure: fWJ19vjRkA3hAkE5S6aE0UmpzVp37h6I5lnz9z+p0QZZ7aw8cfKRhtZq6yyVjtd+HoLzasTwoc537VFblx8NiGNIWUHBVcfGc/Kv56vGY6vTxvTx5J50UptKIn4WEpO8iVXWYdeBOtsvp7zJgRscQxryEXKMCGm3x1Don5kmoE3PNhQBGGU08+0Nc5NtBs0FVu4QiXw6Ui9e/JVakIy8M2rtVHfylMS+uo7BA1Wn97vzUfbB9VTpTxCMevFUcpeE8c399MxHdsEpOQKDz6f/v2nrLobPWifPkA5spYwyVApNUVCkwMk5Gv/0GSVqDcKmTBLQ7E9SCjm21tkWnxLZKDhmA7auW4K2m1JiseSODmz82oCGsf6ruBWGWRF9VV5eouTqVl6jiL3NNiGjJZphBU+fzlCT2DSr1VZL2KMH6QuyZ5N0tOFalZo1jJcj+8fNrS0bzB4tdhdHTBPOZg0c5uhnJnHnN38VNwilNagc8946Lud3z1LbaceXo62JeEmVSMxQLEkZ+uevH0LWo+/jvSrKXBYc9UBJog1183TSC+xnanGHpWHDBbk7PzRvcVFrSnHebIbLt7t6MMtJ/c3WZidPg5UnC6i2v39CuIaFihHebnDH/h7bnOkUUN5Kv4ZwMj86rVKLkj1nwpFss8mXGflYquJ2JCv+kMmZS440qDs=
  - secure: TOLoS3YpftmBm55HwcCPtU8PuT88CxhmZwWZAgdIQtB3YuNcc9B6Afl3b+mu5DX3vDsExq1w5R30s7v7AEkZYCk0wxodtNrGz5Cxorcn8BAh7fe0vhgiW/jyZhV4C2lbvNFgQ9XwWY9JaQtZCTRKHo8NonbCqk9v4QRV1IfLSQ+Nfex9k9aKHU11xqvrspV+rJc6kdvTYiIkxPK+Zy+FfqFWw8SI7Ylz7b6PYeLs9ZCe9yqkrtHdD9qLjzo6wNerWBt6TVn0QWmTCNe87X8+akqTQi7Ccv3fdxx7Cbn7DMEH91i1MjAlafKfNpsMrpfWK1y+MfhyBW42vw06j0hcYC0QLkjGDBWWiFQYejr9ZYIGWjlb3sYnO6FpshXG6VM/Ko6UL4uIE4DKwnE2UsW5xXsl9eulwHxJPtLaAHr2dvn5VPAc//hsycpWe5xyEaXvg8dRyrQ6ysmDlfnhsfBrZlwCIbiUwIoKsK/beT7DfZ0wNLyoPd9FNuQlF3C6dEnk8j6ksfrssHZf313fiIUjcWh3CJUPW6Jayr0s7vkp0LWdPnfHX99ZdGwGYsiQlY00EqPoQnQgidnADohkxMLdB/3gLbdUECsHamTIjNdbBSIhIZJEuSS014ELb1nZo6a4MLPvUm8DH7wkMlYejKt7kPBp5CrxFQa//l/fn14xOB0=
