
language: c
sudo: false
os: linux
dist: bionic

before_install:
  - sudo apt-get update
  - sudo apt-get -y install libmpfr6 nasm

script: bash ./ci/travis-build.sh

# cache:
#   directories:
#   - toolchains

env:
  matrix:
  - ARCH=x86_64
  - ARCH=i686
  global:
  - CI=1
