name: Build nightingale

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install OS dependancies
        run: |
          sudo apt-get update
          sudo apt-get upgrade
          sudo apt-get install git make cmake ninja-build ruby xorriso mtools qemu-system wget
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 18
      - name: build
        run: |
          cmake -Bbuild -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=toolchain/CMake/CMakeToolchain.txt
          cmake --build build
      - name: Upload ISO
        uses: actions/upload-artifact@v2
        with:
          name: ngos.iso
          path: ngos.iso
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ngos.iso
