name: Build nightingale

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install OS dependancies
        run: |
          sudo apt update
          sudo apt install git make cmake ninja-build ruby clang lld xorriso mtools qemu-system
      - name: build
        run: make
      - name: Upload ISO
        uses: actions/upload-artifact@v2
        with:
          name: ngos.iso
          path: ngos.iso
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ngos.iso

  build-with-gcc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install OS dependancies
        run: |
          sudo apt update
          sudo apt install git make cmake ninja-build ruby clang lld xorriso mtools qemu-system
          sudo apt install gcc g++ libgmp-dev libmpfr-dev libmpc-dev bison flex wget patch
      - name: build with clang to install headers
        run: make
      - name: make toolchain directory
        run: mkdir -p ~/.local/bin
      - name: add toolchain to PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: build patched gcc
        run: bash script/build_toolchain.bash
      - name: build
        run: USE_GCC=1 make
