name: Build nightingale

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install OS dependancies
        run: |
          sudo apt update
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo add-apt-repository -y "deb https://apt.llvm.org/jammy/ llvm-toolchain-jammy main"
          sudo apt-get update
          sudo apt-get upgrade
          sudo apt install git make cmake ninja-build ruby clang lld xorriso mtools qemu-system
      - name: build
        run: make
      - name: Upload ISO
        uses: actions/upload-artifact@v2
        with:
          name: ngos.iso
          path: ngos.iso
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ngos.iso
